[local]
localhost ansible_connection=local

[aws]
13.48.44.255 ansible_user=ubuntu ansible_ssh_private_key_file=/var/jenkins_home/store-management-key.pem ansible_ssh_common_args='-o StrictHostKeyChecking=no'